name: customer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  country_code_picker: ^2.0.2
  matrix4_transform: ^2.0.0
  flutter_balloon_slider: ^0.1.1
  carousel_slider: ^4.0.0
  shared_preferences: 
  firebase_core: 
  # firebase_messaging:
  # firebase_database:
  firebase_auth: 
  pinput: ^1.2.0
  # dio:
  flutter_polyline_points:
  google_maps_flutter: ^2.0.05
  # location: ^4.0.0
  firebase_messaging:
  flutter_native_timezone:
  http:
  convert:
  image_picker:
  provider:
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  device_info_plus: ^3.0.1
  badges: ^2.0.2
  json_annotation: ^3.1.0
  circular_countdown_timer: ^0.2.1
  # built_value: ^6.7.1
  
  
  

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.5.1
  # built_value_generator: ^6.7.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/user_logo.png
    - assets/images/vendor_logo.png
    - assets/images/Menu.png
    - assets/images/Wallet.png
    - assets/images/Bag.png
    - assets/images/DangerCircle.png
    - assets/images/Paper.png
    - assets/images/Setting.png
    - assets/images/distance.png
    - assets/images/Search.png
    - assets/images/Filter.png
    - assets/images/foodimages/food1.png
    - assets/images/Star.png
    - assets/images/arrow_right.png
    - assets/images/Home.png
    - assets/images/nav2.png
    - assets/images/Heart.png
    - assets/images/Subtract.png
    - assets/images/redCircle.png
    - assets/images/Camera.png
    - assets/images/Call.png
    - assets/images/Profile.png
    - assets/images/Vector.png
    - assets/images/foodimages/kfc.png
    - assets/images/foodimages/order_image.png
    - assets/images/foodimages/gradient_image.png
    - assets/images/foodimages/left_arrow.png
    - assets/images/foodimages/halal_logo.png
    - assets/images/timer.png
    - assets/images/timeCircle.png
    - assets/images/foodimages/product.png
    - assets/images/foodimages/Heart.png
    - assets/images/foodimages/slider_image1.png
    - assets/images/chevron_left.png
    - assets/images/share_icon.png
    - assets/success1.png
    - assets/success2.png
    - assets/success3.png
    - assets/success4.png
    - assets/failure1.png
    - assets/failure2.png
    - assets/failure3.png
    - assets/failure4.png
    # - assets/images/rider_logo.png
  # To add assets to your application, add an assets section, like this:
    - assets/r_assets/images/Filter.png
    - assets/r_assets/images/Search.png
    - assets/r_assets/images/Setting.png
    - assets/r_assets/images/Wallet.png
    - assets/r_assets/images/Category.png
    - assets/r_assets/images/Vector.png
    - assets/r_assets/images/foodimages/kfc.png
    - assets/r_assets/images/foodimages/order_image.png
    - assets/r_assets/images/foodimages/halal_logo.png
    - assets/r_assets/images/foodimages/left_arrow.png
    - assets/r_assets/images/foodimages/gradient_image.png
    - assets/r_assets/images/foodimages/timeicon.png
    - assets/r_assets/images/Menu.png
    - assets/r_assets/images/timeCircle.png
    - assets/r_assets/images/redCircle.png
    - assets/r_assets/images/Subtract.png
    - assets/r_assets/images/Profile.png
    - assets/r_assets/images/Camera.png
    - assets/r_assets/images/Call.png
    - assets/r_assets/images/category_image.png
    - assets/r_assets/images/foodimages/Delete1.png
    - assets/r_assets/images/rider_logo.png
    - assets/r_assets/images/Chat.png
    - assets/r_assets/chat_image.png
    - assets/r_assets/images/happy.png
    - assets/r_assets/images/Send.png
    - assets/r_assets/images/subtract_image.png
    - assets/r_assets/images/vehicle.png
    - assets/r_assets/images/leaf.png
    - assets/r_assets/images/Star.png
    - assets/r_assets/images/checkgreen.png
    - assets/r_assets/images/arrowright.png
    - assets/r_assets/images/Calendar.png
    - assets/r_assets/images/greycheck.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
